variables:
  BUCKET_NAME: john-practor-millinery-app

stages:
  - build
  - deploy

cache:
  paths:
    - node-modules/
    - vendor/

build:
  image: node:latest
  script:
    - npm install
    - npm run build

deploy:
  image: python:latest
  script: 
    - pip awscli 
    - aws s3 cp ./public/ s3://$BUCKET_NAME/ --recursive
  only:
    - master