image: node:latest

variables:
  AWS_DEFAULT_REGION: eu-west-2
  BUCKET_NAME: john-practor-millinery-app

cache:
  paths:
    - node-modules/
    - vendor/

before_script:
  - npm install aws-cli --save-dev
  - npm install
  - npm run build

deploy:
  script: 
    - aws s3 cp ./public/ s3://$BUCKET_NAME/ --recursive
  only:
    - master