image: ruby:2.3

variables:
  AWS_DEFAULT_REGION: eu-west-2
  BUCKET_NAME: john-proctor-app

cache:
  paths:
    - vendor/

before_script:
  - pip install awscli
  - bundle install --path vendor

deploy:
  script: 
    - bundle exec dato dump
    - bundle exec dato jekyll build
    - aws s3 cp ./public/ s3://$BUCKET_NAME/ --recursive
  only:
    - master